services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Thimphu
    volumes:
      - /home/yeshey/docker_images/smokeping/config:/config
      - /home/yeshey/docker_images/smokeping/data:/data
    ports:
      - 8090:80
    restart: no

